### PR TITLE
Move accounting links into the Accounts section

### PR DESCRIPTION
**Pull request by tbalthazar**

### CODE REVIEW

**Comment by Psycojoker** [comment]
Thanks <3

**Comment by Psycojoker** [comment]
If you are still motivate by this task there is doing the same with https://github.com/Neutrinet/cube_ordering_interface linking to "/admin2"

**Comment by Psycojoker** [comment]
Otherwise I have maybe more interesting tasks

**Comment by tbalthazar** [comment]
Sure, what I propose is that you create Github issues for all those tasks you have in mind, mention me (@tbalthazar) in the comment or assign it to me, so I can pick one when I have time. This way we can discuss (aka I can ask for help) in the context of an issue.

**Pull request merged**
